### ISSUE TITLE
FroMetal textures and particle effects missing

### ISSUE THREAD

**Issue by ghost** [thedefside/journey_to_valhalla#10]
I ran Journey To Valhalla (1.1.3) on its own locally with no other mods or texture replacements and all FroMetal textures., except the warhammer and the buckler are missing textures. Also all FroMetal weapons have broken/missing particle effects.

Tested starting new local game with only Journey To Valhalla and spawning in all FroMetal items using "EasySpawner by Cooleyy". FlaMetal items still look good and appear to be working just fine.

**Comment by thedefside** [comment]
Are you using Vulkan?

**Comment by ghost** [comment]
Not normally no, I set the -force-vulkan to try it out, but still the same result.

**Comment by thedefside** [comment]
The Warhammer and the buckler are the only ones I created. The rest are from the Epic Valheim Additions mod

**Comment by ghost** [comment]
Yup those are the only ones that work. I tried Epic Valheim Additions mod on its own and it is showing the same issue. I will try older version of that mod to see if any work for me and raise the issue with the mod maker Huntard.
Thanks!

**Comment by thedefside** [comment]
That is a pretty popular mod, so I think there might be an issue with the gfx on your PC. Try updating your gpu driver. Steam also has a setting that caches shaders. You could try disabling that.

**Comment by ghost** [comment]
I'm on most recent version of nvidia drivers 516.59 and I turned steam shader caching off, no changes. We'll see if the other mod author has any ideas why it works fine in version 1.7.2 of EpicValheimAdditions but nothing more recent than that.

**Comment by ghost** [comment]
The mod author updated his mod and it fixed the missing textures and particle effects with version 1.8.3. All resolved now.
Thanks!

**Comment by ghost** [comment]
Its affecting the other 2 people I play your Journey to Valhalla mod with.
I tested the Epic Valheim Additions mod and it works fine on version 1.7.2.
Once I update past that version it breaks.
