### ISSUE TITLE
JTV Compability with new valheim patch

### ISSUE THREAD

**Issue by Satty1997** [thedefside/journey_to_valhalla#11]
There are some errors with new valheim mistlands update, So it would be great if you could make it compatible , and find a workaround so we can have the new mistlands added biome, without the one in the mod and still acces the other 2 biomes, their weapons, armours, ores that JTV adds.
Me and my friends would really appreciate it, as we love your modpack and play it since 6 months.

**Comment by maximetinu** [comment]
Yes please, +1000!

**Comment by thedefside** [comment]
I tested it and didn't get any errors but there is still more to do!
