### ISSUE TITLE
Yes please, +1000!

### ISSUE THREAD

**Issue by Satty1997** [thedefside/journey_to_valhalla#12]
Yes please, +1000!

_Originally posted by @Maximetinu in https://github.com/thedefside/journey_to_valhalla/issues/11#issuecomment-1345421831_
      
He just updated it !!So cool to see, love this guy

**Comment by maximetinu** [comment]
Ohhhhh that's awesome! 

But I don't know how to install the mod. In the latest changelog it says "Removed Terraheim" but this is still part of the installation guide:

> In your plugins folder, create a folder named 'DasSauerkraut-Terraheim. Place all the Terraheim files in there.

😖

**Comment by Satty1997** [comment]
> Ohhhhh that's awesome!
> 
> But I don't know how to install the mod. In the latest changelog it says "Removed Terraheim" but this is still part of the installation guide:
> 
> > In your plugins folder, create a folder named 'DasSauerkraut-Terraheim. Place all the Terraheim files in there.
> 
> 😖

Yes, terraheim is a mod from other author which didn't update it for a long time so it is outdated now and causes errors, so JTV no longer uses it.Just remove all your files,configs and mods that you had with old JTV and reinstall all mods/dependencies newest versions from thunderstore: https://valheim.thunderstore.io/package/thedefside/Journey_To_Valhalla/

**Comment by thedefside** [comment]
> Ohhhhh that's awesome!
> 
> But I don't know how to install the mod. In the latest changelog it says "Removed Terraheim" but this is still part of the installation guide:
> 
> > In your plugins folder, create a folder named 'DasSauerkraut-Terraheim. Place all the Terraheim files in there.
> 
> 😖

Oh, I forgot to remove that part from the readme. Just ignore it for now.
