### ISSUE TITLE
Elder Boss Spawn Incorrect

### ISSUE THREAD

**Issue by KitPickles** [thedefside/journey_to_valhalla#13]
Hi there. I'm hoping someone could help me out with this. My friend hosts a dedicated server for us where we recently started a new, mildly modded playthrough with some light QOL mods (OdinsQOL, Multiuser Chest, Advanced Boating, Floating Items, Better Ladders and other small mods of similar nature to remove some of the annoyances of the game). Then we stumbled across JTV and loved the sound of it. Followed all of the instructions, installed Upgrade World and ran the two commands to get the existing world updated and everything said it was successful in the console.

The trouble we're running into is that the boss map markers are not showing up. We had beaten Eikthyr before installing JTV so those are just fine. However, we have found the stone to reveal the location to the Elder and there is no alter there. Instead, there are Burial Chambers. I even popped our seed into the online map viewer to try to find others and each of those were also Burial Chambers. Is it safe to assume that we need to start over with our world because the boss spawns are corrupt, or is there a fix for this. Any help would be greatly appreciated. If any more info is necessary, please let me know and I'll do my best to provide it. Thanks!

**Comment by thedefside** [comment]
I've seen this happen before with the EVA altars. It's poosible the IG change the algorithm for placing altars in one of the updates. The alrir locations are usually only determined when the world is created, but with upgrade world you can have them determined again. Try going back to the Vegvisirs that gave you the location. It should give you the new location now.

**Comment by KitPickles** [comment]
That fixed it up. Turns out we had to restart the server after running the command as well. The first Vegvisir we found for the elder gave us an updated location and the altar was there. Thank you so much for that suggestion and for the help. The pack is fantastic and we really are having a lot of fun with the additions!
