### ISSUE TITLE
Vanilla Armor issues

### ISSUE THREAD

**Issue by Trey122** [thedefside/journey_to_valhalla#14]
For some reason bronze/iron armor does not show up to be crafted even though I have all the req mats and crafting stations

**Comment by thedefside** [comment]
Are you talking about vanilla armor?

**Comment by Trey122** [comment]
Yes

**Comment by thedefside** [comment]
Did you follow the install instructions? Do you have other mods installed? Have you checked your log for errors? There's nothing in JTV that changes any vanilla recipes

**Comment by thedefside** [comment]
Closed since no response
