### ISSUE TITLE
WorldGen missing or null.

### ISSUE THREAD

**Issue by devdave** [thedefside/journey_to_valhalla#17]
[Error  : Unity Log] 03/28/2023 10:21:03: The WorldGenerator instance was null

[Error  : Unity Log] NullReferenceException: The WorldGenerator instance was null
Stack trace:
Heightmap.Generate () (at <bf16ee947009431fb40ab69e41500aeb>:0)
(wrapper dynamic-method) Heightmap.DMD<Heightmap::Regenerate>(Heightmap)
Heightmap.OnEnable () (at <bf16ee947009431fb40ab69e41500aeb>:0)

Any chance this coming from the JTV ecosystem?

**Comment by thedefside** [comment]
Update your Bepinex
