### ISSUE TITLE
Banana Texture Conflict

### ISSUE THREAD

**Issue by mitchelljtroyer** [thedefside/journey_to_valhalla#18]
[Warning:Jotunn.Managers.PrefabManager] Failed to clone prefab, name already exists: Banana
[Error : jtv.Jtv] Object reference not set to an instance of an object at jtv.Jtv.AddItems () [0x00120] in :0

Game works just fine but I receive this error in logs while playing.

Submitted to Jotunn and was told:

"This is likely a mod conflict between 'Journey To Valhalla' and another mod. Internal item names must be unique because the game identifies them by their prefab name, thus an error is thrown here.

Please open a new issue at the [Journey To Valhalla](https://github.com/thedefside/journey_to_valhalla) repo."

**Comment by thedefside** [comment]
If you want to be able to craft the recipe and get rid of this error you will have to uninstall whatever other mod you have that adds bananas.

**Comment by mitchelljtroyer** [comment]
Thank you! I'm running Fruit Trees as well as Odin's Food Barrels. I'll double check both

**Comment by mitchelljtroyer** [comment]
The issued was caused by https://valheim.thunderstore.io/package/Horem/Fruit_Trees/
