### ISSUE TITLE
Armorer's Bench recipes issuses

### ISSUE THREAD

**Issue by MacMi39** [thedefside/journey_to_valhalla#3]
hello, sr for my bad English. I have an issue that, the armorer's bench with the strange recipe.
-here is the logoutput and the recipe: [LogOutput.log](https://github.com/thedefside/journey_to_valhalla/files/7818796/LogOutput.log)
![image](https://user-images.githubusercontent.com/97204361/148314151-801fcb04-4cdd-4e5b-8508-735e361ed400.png)

**Comment by thedefside** [comment]
This is the correct recipe. You should not craft it. It currently has no use.
