### ISSUE TITLE
conflict Terraheim and EpicValheimsAdditions

### ISSUE THREAD

**Issue by rmcgraw1** [thedefside/journey_to_valhalla#4]
The workbench for Terraheim doesn't show up unless i remove EpicValheimsAdditions is there a way to fix this or remove EpicValheimsAdditions as a dependency from JTV

i did go and remove all other mods to make sure that this was the problem

**Comment by thedefside** [comment]
The Terraheim Armorer's bench is not supposed to show up. I've disabled the Terraheim armor changes. By removing Epic Valheim Additions you've broken just about everything. So, no new foods, weapons, armors, or items.

**Comment by rmcgraw1** [comment]
Sorry i didn't realize you intended it that way figured since the bronze armor wasn't showing it was a bug still a great mod pack thanks for the work you do
