### ISSUE TITLE
Mistlands spawns deathsquitos instead of darksquitos

### ISSUE THREAD

**Issue by Jones-Adam** [thedefside/journey_to_valhalla#5]
presumably

In file spawn_that.world_spawners.JTV_Mistlands.cfg
line 46 should read PrefabName = DarkMosquito

**Comment by thedefside** [comment]
This was done intentionally. There is no prefab "DarkMosquito" and you would get errors from spawn that.

**Comment by Jones-Adam** [comment]
isn't that what the file "rrrmonsters.custom.DarkMosquito.json" does? create a prefab called DarkMosquito?

**Comment by thedefside** [comment]
RRRcore is broken so it doesn't do anything.

**Comment by Jones-Adam** [comment]
ahhh...ok I see - so I would need to use something like - https://valheim.thunderstore.io/package/FixItFelix/CreatureCloner/ to first create a new prefab

But it looks like that doesn't yet support quite as many features as RRR did - I suppose there isn't another option available otherwise you would have changed it already...

**Comment by thedefside** [comment]
I will begin the slow process of rebuilding these creatures in code. But that will take quite a bit of time.

**Comment by Jones-Adam** [comment]
looks like there is a reprieve for now :) thanks for all your work on this!
