### ISSUE TITLE
Tamed Animals Invulnerable?

### ISSUE THREAD

**Issue by VaelophisNyx** [thedefside/journey_to_valhalla#6]
After installing the mods for this, I cannot kill tamed animals at all. Butcher's Knife dealing 700-1000+ damage per hit, yet they just dont take any damage?

[logoutput.log](https://github.com/thedefside/journey_to_valhalla/files/8310236/logoutput.log)

**Comment by VaelophisNyx** [comment]
Additionally, enemies cannot damage tamed animals?

**Comment by thedefside** [comment]
I can assure you Journey to Valhalla has been tested thoroughly by hundred of users, and these issues do not happen. You must have other mods installed that are causing these issues.

**Comment by VaelophisNyx** [comment]
Oh I definitely do have other mods. But until I added the ones relevant to this mod/modpack, it was not an issue. I did at least find that campfires can kill them (though it can sometimes take 2+ fires to do so-)

**Comment by thedefside** [comment]
Are you using a mod manager?

**Comment by VaelophisNyx** [comment]
I am not. They never seem to work for me.

**Comment by VaelophisNyx** [comment]
ok so I figured it out. Friend failed to inform me his Valheim Plus config was set for tamed animals to be *immune* to damage but also didnt enable the bypass for the knife.
