### ISSUE TITLE
FPS performance really low

### ISSUE THREAD

**Issue by attckdog** [thedefside/journey_to_valhalla#8]
While playing with this mod pack my everyone on the server is getting 30-40 fps high and lows of even 12 during rain. 
I'm running all graphics settings on the lowest it can go (aside from fps limit naturally) 
base game with bepin I get 80fps

There anything we can disable in the modpack to improve FPS ?

**Comment by thedefside** [comment]
Do you have other mods installed? Or just JTV and it's dependencies?

**Comment by attckdog** [comment]
Turns out I am using Journey To QoLhalla, a different modpack. Sorry for the mistake!

**Comment by thedefside** [comment]
Unfortunately, you will probably have to go through the mods 1 by 1 disabling them to find what is causing your issue.
