### ISSUE TITLE
Spider Lag/ Spider Silk DR

### ISSUE THREAD

**Issue by Maldread** [thedefside/journey_to_valhalla#9]
Spiders spit ability causes massive FPS drop due to particles most likely even with settings all on low. Additionally Spider Silk drop rate seems to have lowered, out of 2 dozen kills only 1 silk dropped, rate needs to be adjusted.

**Comment by thedefside** [comment]
The poison spiders throw vanilla ooze bombs. If the vfx causes frame drops that's something Iron Gate needs to fix. The drop rate on the spider silk hasn't changed.

**Comment by Maldread** [comment]
Odd, additionally is there a prerequisite for using the Mourning Queen Vegvisir? I found 1 laying down and it doesn't seem to do anything.

**Comment by thedefside** [comment]
Yes, you have to provide 5 Cursed Dark Effigies to summon the boss.
